firstWebsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # templates for url
    # /music
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='registration'),

    # /music/<album_id>
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),


]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title+' - '+self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms


class Userform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import Userform
from music.models import Album


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'logo']


class  UserFormView(View):
    form_class = Userform
    template_name = 'music/registration.html'
    # for new user

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form, })
    # process form for data

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user.set_password(password)
            user.save()

            #
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form, })

music/templates/music/album_form.html
{% extends 'music/style_blueprit.html' %}
{% block title %} Add a New Album {% endblock %}
{% block album_active %} active {% endblock %}
{% block body %}
    <div class="container-fluid">

        <div class="row">
            <div class="col-sm-12 col md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button class="btn btn-success" type="submit">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

music/templates/music/detail.html
{% extends 'music/style_blueprit.html' %}
{% block title %} Album Details {% endblock %}
{% block body%}
    <img src="{{ album.logo }}" style="width: 250px;">

    <h1>{{ album.album_title }}</h1>
    <h3>{{ album.artist }}</h3>

        {% for song in album.song_set.all %}
                {{ song.song_title }}
                {% if song.is_fovorite %}
                    <img src="http://vignette2.wikia.nocookie.net/battlefordreamislandfanfiction/images/5/55/Yellow_Star_Idle.png"/>
                {% endif %}
            <br>
        {% endfor %}
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/style_blueprit.html' %}

{% block body%}
        <ul>
            {% for album in all_albums %}
            <li>
                <a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a>
            </li>
            {% endfor %}
        </ul>
{% endblock %}

music/templates/music/registration.html
{% extends 'music/style_blueprit.html' %}
{% block title %} Register {% endblock %}
{% block body %}
    <div class="container-fluid">

        <div class="row">
            <div class="col-sm-12 col md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Create a New Account</h3>
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button class="btn btn-success" type="submit">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

music/templates/music/style_blueprit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Jhaka-Naka {% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" >
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Tangerine">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <!-- Logo -->
      <a class="navbar-brand" href="{% url 'music:index' %}">Jhaka-Naka</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="topNavBar">
      <ul class="nav navbar-nav">
        <li class="active">
            <a href="{% url 'music:index' %}">
                <span class="glyphicon glyphicon-cd" area-hidden="true"></span>&nbsp;
                Albums
            </a>
        </li>

        <li class="">
            <a href="#">
                <span class="glyphicon glyphicon-music" area-hidden="true"></span>&nbsp;
                Songs
            </a>
        </li>
<!-- drop down menu tempalte below:
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>-->
      </ul>
<!-- a form filed for searching -->
      <form class="navbar-form navbar-left" role="search" method="get" action="#">
        <div class="form-group">
          <input type="text" class="form-control" name="q" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-search" area-hidden="true"></span>&nbsp;
            Search
        </button>
      </form>
<!-- right side of nav bar -->
      <ul class="nav navbar-nav navbar-right">

        <li class="">
            <a href="{% url 'music:album-add' %}">
                <span class="glyphicon glyphicon-plus" area-hidden="true"></span>&nbsp;
                Add Album
            </a>
        </li>

        <li class="">
            <a href="#">
                <span class="glyphicon glyphicon-off" area-hidden="true"></span>&nbsp;
                Log Out
            </a>
        </li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% block body %}
{% endblock %}
</body>
</html>